name: Docker

on:
  workflow_dispatch:
  push:
    branches: [ main ]

env:
  ALIYUN_REGISTRY: "${{ secrets.ALIYUN_REGISTRY }}"
  ALIYUN_NAMESPACE: "${{ secrets.ALIYUN_NAMESPACE }}"
  ALIYUN_REGISTRY_USER: "${{ secrets.ALIYUN_REGISTRY_USER }}"
  ALIYUN_REGISTRY_PASSWORD: "${{ secrets.ALIYUN_REGISTRY_PASSWORD }}"

jobs:
  build:
    name: Pull
    runs-on: ubuntu-latest
    steps:
    - name: Before freeing up disk space
      run: |
        echo "Before freeing up disk space"
        echo "=============================================================================="
        df -hT
        echo "=============================================================================="

    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 2048
        swap-size-mb: 128
        remove-dotnet: 'true'
        remove-haskell: 'true'
        build-mount-path: '/var/lib/docker/'

    - name: Restart docker
      run: sudo service docker restart

    - name: Checkout Code
      uses: actions/checkout@v5

    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v4

    - name: Login to Aliyun ACR
      run: |
        echo "${{ secrets.ALIYUN_REGISTRY_PASSWORD }}" | docker login ${{ secrets.ALIYUN_REGISTRY }} -u ${{ secrets.ALIYUN_REGISTRY_USER }} --password-stdin

    - name: Build and push image Aliyun
      run: |
        while IFS= read -r line || [ -n "$line" ]; do
            # 忽略空行与注释
            [[ -z "$line" ]] && continue
            if echo "$line" | grep -q '^\s*#'; then
                continue
            fi
        
            echo "=== Processing $line ==="
            docker pull $line
            
            # 处理 --platform 参数
            platform=$(echo "$line" | awk -F'--platform[ =]' '{if (NF>1) print $2}' | awk '{print $1}')
            if [ -z "$platform" ]; then
                platform_prefix=""
            else
                platform_prefix="${platform//\//_}_"
            fi

            # 1. 提取完整镜像地址，去掉@sha256后缀
            image_full=$(echo "$line" | awk '{print $NF}')
            image_full="${image_full%%@*}"
            echo "image_full: $image_full"

            # 2. 提取镜像名:tag（终极方案：从右往左取，保留所有内容）
            # 比如 registry.k8s.io/coredns/coredns:v1.10.1 → coredns:v1.10.1
            image_name_tag=$(echo "$image_full" | sed -E 's/.*\///')
            echo "image_name_tag: $image_name_tag"

            # 3. 直接拼接目标地址，不做任何额外处理
            new_image="$ALIYUN_REGISTRY/$ALIYUN_NAMESPACE/$platform_prefix$image_name_tag"
            echo "new_image: $new_image"

            # 打标签并推送
            docker tag $image_full $new_image
            docker push $new_image

            # 清理本地镜像
            docker rmi $image_full
            docker rmi $new_image
        done < images.txt
